name: Build Desktop Apps

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-latest is for arm64 build, macos-13 is for x86_64
        include:
          - os: windows-latest
          - os: macos-latest # arm64
          - os: macos-13 # x86_64
          - os: ubuntu-latest # x86_64 (no arm64 support on GH Actions yet)

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      # Use 3.12 - 3.13 not working yet (Numpy verion too old)
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # Use GH python version (includes TK/TCL)
      - name: Set up Python using GH python version
        run: uv venv --python 3.12 --python-preference only-system

      - name: Install the project
        run: uv sync

      # Compress MacOS app param ignored on other platforms
      - name: Build Desktop App
        run: uv run bash ./app/desktop/build_desktop_app.sh --compress-mac-app

      - name: Build Windows Installer
        if: matrix.os == 'windows-latest'
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: ./app/desktop/WinInnoSetup.iss

      - name: Copy Windows Installer
        if: matrix.os == 'windows-latest'
        run: cp ./app/desktop/Output/kilnsetup.exe ./app/desktop/build/dist/Kiln.Windows.Installer.exe

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: kiln-desktop-${{ runner.os }}-${{ runner.arch }}
          path: ./app/desktop/build/dist/*
